<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/ebene/image/upload/v1554329281/d0df0c42-6695-4099-b3ca-6ddfdd58b498.png" alt="Ebenezer Oyenuga">
                        <h6>Ebenezer Oyenuga</h6>
                        <p>Back-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/ebeneoyen" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/EbenezerOyenuga" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Welcome to my website.Welcome to my profile page for hng intern. My name is OYENUGA, Ebenezer. Got about five years experience in web development and about a year expereince in Data Analysis.</p>
                        <br />
                        <h6>Skills</h6>
                        <p> PHP</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
